services:
  backend-db-test:
    image: postgres:17.2-alpine
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL_TEST}
      POSTGRES_DB: keuangan_desa_test # A separate database name
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
    volumes:
      # This builds your schema (1_init_schema.sql, etc.) on startup
      - ./db/migrations:/docker-entrypoint-initdb.d
    ports:
      # Map to a different port (5433) to avoid conflict with dev DB (5432)
      - "5433:5432"
    networks:
      - prpl-test-network

networks:
  prpl-test-network:
