services:
  backend-db:
    image: postgres:17.2-alpine
    env_file:
      - .env
    volumes:
      - prpl-data:/var/lib/postgresql/data
    networks:
      - prpl-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prpl_koma -d keuangan_desa"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend-api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.prod
    env_file:
      - .env
    depends_on:
      backend-db:
        condition: service_healthy
    networks:
      - prpl-network
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    command: sh -c "./database/scripts/migrate.sh && pnpm run seed && node src/index.js"

networks:
  prpl-network:

volumes:
  prpl-data:
